let shopItemsData = [
  {
    id: "intel_i3_12100f",
    name: "Intel Core i3-12100F",
    price: 229,
    desc: `<i class="bi bi-check-lg"></i> 4 ядра / 8 нишки
    <br><i class="bi bi-check-lg"></i> 3.30 - 4.30 GHz
    <br><i class="bi bi-check-lg"></i> 15MB кеш `,
    img: "../img/CPU/intel_core_i312100f.jpg",
  },
  {
    id: "ryzen_5_3600",
    name: "AMD Ryzen 5 3600",
    price: 229,
    desc: `
    <i class="bi bi-check-lg"></i> 4 ядра / 12 нишки
    <br><i class="bi bi-check-lg"></i> 3.60 - 4.20 GHz
    <br><i class="bi bi-check-lg"></i> 32MB L3 кеш 
    `,
    img: "../../img/CPU/amd_ryzen_5_3600.jpg",
  },
  {
    id: "intel_i5_10400f",
    name: "Intel Core i5-10400F",
    price: 239,
    desc1:`<i class="bi bi-check-lg"></i> 6 ядра / 12 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 2.90 - 4.30 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 12MB кеш `,
    img: "../../img/CPU/intel_core_i510400f.jpg",
  },
  {
    id: "ryzen_5_5600",
    name: "AMD Ryzen 5 5600",
    price: 299,
    desc1:`<i class="bi bi-check-lg"></i> 6 ядра / 12 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 3.50 - 4.40 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 32MB L3 кеш `,
    img: "../../img/CPU/amd_ryzen_5_5600.jpg",
  },
  {
    id: "ryzen_7_5700x",
    name: "AMD Ryzen 7 5700X",
    price: 479,
    desc1:`<i class="bi bi-check-lg"></i> 8 ядра / 16 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 3.40 - 4.60 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 32MB L3 кеш `,
    img: "../../img/CPU/amd_ryzen_7_5700x.jpg",
  },
  {
    id: "intel_i5_11600kf",
    name: "Intel Core i5-11600KF",
    price: 509,
    desc1:`<i class="bi bi-check-lg"></i> 6 ядра / 12 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 3.90 - 4.90 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 12 MB Smart Cache `,
    img: "../../img/CPU/Intel Core i5-11600KF.jpg",
  },
  {
    id: "ryzen_5_7600x",
    name: "AMD Ryzen 5 7600X",
    price: 599,
    desc1:`<i class="bi bi-check-lg"></i> 6 ядра / 12 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 4.70 - 5.30 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 32MB L3 кеш `,
    img: "../../img/CPU/amd_ryzen_5_7600x.png",
  },
  {
    id: "intel_i5_12600kf",
    name: "Intel Core i5-12600KF",
    price: 629,
    desc1:`<i class="bi bi-check-lg"></i> 8 ядра / 16 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 3.70 - 4.90 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 20 MB Intel `,
    img: "../../img/CPU/intel_core_i512600kf.jpg",
  },
  {
    id: "ryzen_9_5950x",
    name: "AMD Ryzen 9 5950X",
    price: 1169,
    desc1:`<i class="bi bi-check-lg"></i> 16 ядра / 32 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 3.40 - 4.90 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 64MB L3 кеш `,
    img: "../../img/Top Products/amd_ryzen_9_5950x.jpg",
  },
  {
    id: "intel_i9_12900ks",
    name: "Intel Core i9-12900KS",
    price: 1499,
    desc1:`<i class="bi bi-check-lg"></i> 16 ядра / 24 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 3.20 - 5.50 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 32 MB Intel `,
    img: "../../img/Top Products/intel_core_i912900ks.jpg",
  },
  {
    id: "intel_i5_13600kf",
    name: "Intel Core i5-13600KF",
    price: 666,
    desc1:`<i class="bi bi-check-lg"></i> 16 ядра / 20 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 2.60 - 5.10 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 24 MB Intel`,
    img: "../../img/CPU/intel_core_i513600kf.jpg",
  },
  {
    id: "intel_i7_13700kf",
    name: "Intel Core i7-13700KF",
    price: 929,
    desc1:`<i class="bi bi-check-lg"></i> 16 ядра / 24 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 3.40 - 5.40 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 30 MB Intel `,
    img: "../../img/CPU/intel_core_i713700kf.png",
  },
  {
    id: "intel_i7_13700k",
    name: "Intel Core i7-13700K",
    price: 949,
    desc1:`<i class="bi bi-check-lg"></i> 16 ядра / 24 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 3.40 - 5.40 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 30 MB Intel `,
    img: "../../img/CPU/intel_core_i713700k.png",
  },
  {
    id: "intel_i9_12900kf",
    name: "Intel Core i9-12900KF",
    price: 1119,
    desc1:`<i class="bi bi-check-lg"></i> 24 ядра / 32 нишки`,
    desc2:`<i class="bi bi-check-lg"></i> 5.20 GHz`,
    desc3:`<i class="bi bi-check-lg"></i> 30 MB Intel Smart `,
    img: "../../img/CPU/intel_core_i912900kf.jpg",
  },
  {
    id: "rtx_3050",
    name: "GeForce RTX 3050",
    price: 639,
    desc1:`<i class="bi bi-check-lg"></i> 8GB GDDR6`,
    desc2:`<i class="bi bi-check-lg"></i> 128-bit`,
    desc3:`<i class="bi bi-check-lg"></i> 3x DisplayPort`,
    img: "../../img/GPU/rtx_3050.png",
  },
  {
    id: "rx_6600",
    name: "ASRock Radeon RX 6600",
    price: 547,
    desc1:`<i class="bi bi-check-lg"></i> 8GB GDDR6`,
    desc2:`<i class="bi bi-check-lg"></i> 128-bit`,
    desc3:`<i class="bi bi-check-lg"></i> 1x DisplayPort`,
    img: "../../img/GPU/rx_6600.png",
  },
  {
    id: "rx_6700",
    name: "ASRock Radeon RX 6700",
    price: 1009,
    desc1:`<i class="bi bi-check-lg"></i> 12GB GDDR6`,
    desc2:`<i class="bi bi-check-lg"></i> 192-bit`,
    desc3:`<i class="bi bi-check-lg"></i> 1x DisplayPort`,
    img: "../../img/GPU/rx_6700_xt.png",
  },
  {
    id: "TG_8gb",
    name: "8GB 2666MHz DDR4 Team Group",
    price: 47,
    desc1:`<i class="bi bi-check-lg"></i> 8GB`,
    desc2:`<i class="bi bi-check-lg"></i> DDR4`,
    desc3:`<i class="bi bi-check-lg"></i> 2666Mhz`,
    img: "../../img/RAM/team_group_8gb.jpg",
  },
  {
    id: "GSKILL_8gb",
    name: "8GB DDR4 3200 G.SKILL",
    price: 49,
    desc1:`<i class="bi bi-check-lg"></i> 8GB`,
    desc2:`<i class="bi bi-check-lg"></i> DDR4`,
    desc3:`<i class="bi bi-check-lg"></i> 3200Mhz`,
    img: "../../img/RAM/gskill_8gb.png",
  },
  {
    id: "XPG_16gb",
    name: "16GB DDR4 3600MHz XPG",
    price: 109,
    desc1:`<i class="bi bi-check-lg"></i> 16GB`,
    desc2:`<i class="bi bi-check-lg"></i> DDR4`,
    desc3:`<i class="bi bi-check-lg"></i> 3600Mhz`,
    img: "../../img/RAM/xpg_16gb.png",
  },
  {
    id: "A520M",
    name: "MSI A520M-A PRO",
    price: 119,
    desc1:`<i class="bi bi-check-lg"></i> AMD A520`,
    desc2:`<i class="bi bi-check-lg"></i> AMD AM4`,
    desc3:`<i class="bi bi-check-lg"></i> HDMI/DVI`,
    img: "../../img/MotherBoard/msi_a520ma_pro.png",
  },
  {
    id: "H510M",
    name: "ASRock H510M-HDV R2.0",
    price: 139,
    desc1:`<i class="bi bi-check-lg"></i> LGA 1200`,
    desc2:`<i class="bi bi-check-lg"></i> Intel H510`,
    desc3:`<i class="bi bi-check-lg"></i> HDMI/DVI-D`,
    img: "../../img/MotherBoard/asrock_h510mhdv_r20.png",
  },
  {
    id: "B660M",
    name: "GIGABYTE B660M GAMING X DDR4",
    price: 279,
    desc1:`<i class="bi bi-check-lg"></i> Intel B660`,
    desc2:`<i class="bi bi-check-lg"></i> LGA 1700`,
    desc3:`<i class="bi bi-check-lg"></i> DisplayPort/HDMI`,
    img: "../../img/MotherBoard/gigabyte_b660m_gaming_x_ddr4.png",
  },
  {
    id: "A650BN",
    name: "MSI MAG A650BN 650W Bronze",
    price: 129,
    desc1:`<i class="bi bi-check-lg"></i> 650W Plus Bronze`,
    desc2:`<i class="bi bi-check-lg"></i> 120мм вентилатор`,
    desc3:`<i class="bi bi-check-lg"></i> Active PFC`,
    img: "../../img/PSU/msi_mag_a650bn.png",
  },
  {
    id: "GEC",
    name: "COUGAR GEC 650 650W Gold",
    price: 139,
    desc1:`<i class="bi bi-check-lg"></i> 650W`,
    desc2:`<i class="bi bi-check-lg"></i> 80 Plus Gold`,
    desc3:`<i class="bi bi-check-lg"></i> 1х вентилатор 120 мм`,
    img: "../../img/PSU/cougar_gec_650_650w_gold.png",
  },
  {
    id: "ZM500",
    name: "Zalman MegaMax ZM500-TXII 500W",
    price: 96,
    desc1:`<i class="bi bi-check-lg"></i> 500W`,
    desc2:`<i class="bi bi-check-lg"></i> Вентилатор 120мм`,
    desc3:`<i class="bi bi-check-lg"></i> 80 PLUS`,
    img: "../../img/PSU/zalman_megamax_500w_zm500txii.jpg",
  },
  //SSD
  {
    id: "SSD980",
    name: "1TB Samsung 980 Pro M.2 NVMe",
    price: 239,
    desc1:`<i class="bi bi-check-lg"></i> 1TB`,
    desc2:`<i class="bi bi-check-lg"></i> 7000 MB/сек четене`,
    desc3:`<i class="bi bi-check-lg"></i> 5000 MB/сек запис`,
    img: "../../img/SSD/1tb_samsung_980_pro_pcie_40.png",
  },
  {
    id: "SSD870",
    name: "SAMSUNG SSD 870 EVO 500GB",
    price: 109,
    desc1:`<i class="bi bi-check-lg"></i> 500GB`,
    desc2:`<i class="bi bi-check-lg"></i> 560 MB/s четене`,
    desc3:`<i class="bi bi-check-lg"></i> 530 MB/s запис`,
    img: "../../img/SSD/samsung_ssd_870_evo_500gb.jpg",
  },
  {
    id: "SSD980V",
    name: "500GB Samsung SSD 980 PCIe 3.0",
    price: 109,
    desc1:`<i class="bi bi-check-lg"></i> 500GB`,
    desc2:`<i class="bi bi-check-lg"></i> 3100 MB/s четене`,
    desc3:`<i class="bi bi-check-lg"></i> 2600 MB/s писане`,
    img: "../../img/SSD/500gb_samsung_ssd_980_pcie_30.jpg",
  },
  
];
