export let  shopItemsData = [
  {
    id: "intel_i3_12100f",
    name: "Intel Core i3-12100F",
    img: "../../img/CPU/intel_core_i312100f.jpg",
    url: "../../Components/CPU/i3-12100f.html",
  },
  {
    id: "ryzen_5_3600",
    name: "AMD Ryzen 5 3600",
    img: "../../img/CPU/amd_ryzen_5_3600.jpg",  
    url: "../../Components/CPU/Ryzen-5-3600.html",
  },
  {
    id: "intel_i5_10400f",
    name: "Intel i5-10400F",
    img: "../../img/CPU/intel_core_i510400f.jpg",
    url: "../../Components/CPU/i5-10400f.html"
  },
  {
    id: "ryzen_5_5600",
    name: "AMD Ryzen 5 5600",
    img: "../../img/CPU/amd_ryzen_5_5600.jpg",
    url: "../../Components/CPU/Ryzen-5-5600.html",
    
  },
  {
    id: "ryzen_7_5700x",
    name: "AMD Ryzen 7 5700X",
    img: "../../img/CPU/amd_ryzen_7_5700x.jpg",
    url: "../../Components/CPU/Ryzen-7-5700x.html", 
  },
  {
    id: "intel_i5_11600kf",
    name: "Intel Core i5-11600KF",
    img: "../../img/CPU/Intel Core i5-11600KF.jpg",
    url: "../../Components/CPU/i5-11600kf.html"

  },
  {
    id: "ryzen_5_7600x",
    name: "AMD Ryzen 5 7600X",
    img: "../../img/CPU/amd_ryzen_5_7600x.png",
    url: "../../Components/CPU/Ryzen-5-7600x.html",
  },
  {
    id: "intel_i5_12600KF",
    name: "Intel Core i5-12600KF",
    img: "../../img/CPU/intel_core_i512600kf.jpg",
    url: "../../Components/CPU/i5-12600kf.html", 
  },
  {
    id: "ryzen_9_5950x",
    name: "AMD Ryzen 9 5950X",
    img: "../../img/CPU/amd_ryzen_9_5950x.jpg",
    url: "../../Components/CPU/Ryzen-9-5950x.html", 
  },
  {
    id: "intel_i9_12900ks",
    name: "Intel Core i9-12900KS",
    img: "../../img/Top Products/intel_core_i912900ks.jpg",
    url: "../../Components/CPU/i9-12900ks.html", 
  },
  {
    id: "intel_i5_13600kf",
    name: "Intel Core i5-13600KF",
    img: "../../img/CPU/intel_core_i513600kf.jpg",
    url: "../../Components/CPU/i5-13600kf.html", 
  },
  {
    id: "intel_i7_13700kf",
    name: "Intel Core i7-13700KF",
    img: "../../img/CPU/intel_core_i713700kf.png",
    url: "../../Components/CPU/i7-13700kf.html",
  },
  {
    id: "intel_i7_13700k",
    name: "Intel Core i7-13700K",
    img: "../../img/CPU/intel_core_i713700k.png",
    url: "../../Components/CPU/i7-13700k.html", 
  },
  {
    id: "intel_i9_12900kf",
    name: "Intel Core i9-12900KF",
    img: "../../img/CPU/intel_core_i912900kf.jpg",
    url: "../../Components/CPU/i9-12900kf.html",
  },
  {
    id: "intel_i9_13900kf",
    name: "Intel Core i9-13900KF",
    img: "../../img/CPU/intel_core_i913900kf.png",
    url: "../../Components/CPU/i9-13900kf.html", 
  },
  {
    id: "ryzen_9_5950",
    name: "AMD Ryzen 9 5950",
    img: "../../img/CPU/amd_ryzen_9_5950x.jpg",
    url: "../../Components/CPU/Ryzen-9-5950.html", 
  },
  {
    id: "ryzen_9_7950x",
    name: "AMD Ryzen 9 7950X",
    img: "../../img/CPU/amd_ryzen_9_7950x.png",
    url: "../../Components/CPU/Ryzen-9-7950x.html", 
  },
  {
    id: "ryzen_7_5800x3d",
    name: "AMD Ryzen 7 5800X3D",
    img: "../../img/CPU/amd_ryzen_7_5800x3d.png",
    url: "../../Components/CPU/Ryzen-7-5800x3d.html", 
  },
  {
    id: "rtx_3050",
    name: "GeForce RTX 3050",
    img: "../../img/GPU/rtx_3050.png",
    url: "../../Components/GPU/rtx-3050.html", 
  },
  {
    id: "rx_6600",
    name: "ASRock Radeon RX 6600",
    img: "../../img/GPU/rx_6600.png",
    url: "../../Components/GPU/rx-6600.html",
  },
  {
    id: "rx_6700",
    name: "ASRock Radeon RX 6700",
    img: "../../img/GPU/rx_6700_xt.png",
    url: "../../Components/GPU/rx-6700.html",
  },
  {
    id: "rx_6750",
    name: "MSI Radeon RX 6750",
    img: "../../img/GPU/rx_6750.png",
    url: "../../Components/GPU/rx-6750.html",
  },
  {
    id: "rtx_4090",
    name: "GAINWARD RTX 4090",
    img: "../../img/Top Products/MSI_RTX_4090.png",
    url: "../../Components/GPU/rtx-4090.html",
  },
  {
    id: "msi_rtx_4090",
    name: "MSI GeForce RTX 4090",
    img: "../../img/Top Products/MSI_RTX_4090_Trio.png",
    url: "../../Components/GPU/msi_rtx-4090.html",
  },
  {
    id: "TG_8gb",
    name: "8GB 2666MHz DDR4 Team Group",
    img: "../../img/RAM/team_group_8gb.jpg",
    url: "../../Components/RAM/TeamGroup-8gb.html",
  },
  {
    id: "GSKILL_8gb",
    name: "8GB DDR4 3200 G.SKILL",
    img: "../../img/RAM/gskill_8gb.png",
    url: "../../Components/RAM/GSKILL-8gb.html",
  },
  {
    id: "XPG_16gb",
    name: "16GB DDR4 3600MHz XPG",
    img: "../../img/RAM/xpg_16gb.png",
    url: "../../Components/RAM/XPG-16gb.html",
  },
  {
    id: "XPG_DDR5",
    name: "16GB DDR5 5200МHz XPG",  
    img: "../../img/RAM/xpg_black_16gb.png",
    url: "../../Components/RAM/XPG-DDR5.html",
  },
  {
    id: "kingston_32gb",
    name: "32GB DDR5 5200MHz Kingston FURY",  
    img: "../../img/RAM/kingston_32gb_ddr5.png",
    url: "../../Components/RAM/Kingston-32gb.html",
  },
  {
    id: "kingston_2x16gb",
    name: "32GB (2x16GB) 3600MHz DDR4 Kingston FURY",  
    img: "../../img/RAM/kingston_2x16_ddr4.jpg",
    url: "../../Components/RAM/Kingston-2x16gb.html",
  },
  {
    id: "A520M",
    name: "MSI A520M-A PRO",
    img: "../../img/MotherBoard/msi_a520ma_pro.png",
    url: "../../Components/MotherBoard/A520M.html",
  },
  {
    id: "H510M",
    name: "ASRock H510M-HDV R2.0",
    img: "../../img/MotherBoard/asrock_h510mhdv_r20.png",
    url: "../../Components/MotherBoard/H510M.html",
  },
  {
    id: "B660M",
    name: "GIGABYTE B660M GAMING X DDR4",
    img: "../../img/MotherBoard/gigabyte_b660m_gaming_x_ddr4.png",
    url: "../../Components/MotherBoard/B660M.html",
  },
  {
    id: "B760M",
    name: "GIGABYTE B760M GAMING",
    img: "../../img/MotherBoard/gigabyte_b760m_gaming.png",
    url: "../../Components/MotherBoard/B760M.html",
  },
  {
    id: "B550M",
    name: "Gigabyte B550M Aorus Elite V2",
    img: "../../img/MotherBoard/gigabyte_b550m_aorus_elite_v2.png",
    url: "../../Components/MotherBoard/B550M.html",
  },
  {
    id: "B560M",
    name: "ASUS ROG STRIX B560-G GAMING WIFI",
    img: "../../img/MotherBoard/asus_rog_strix_b560g_gaming_wifi.png",
    url: "../../Components/MotherBoard/B560M.html",
  },
  {
    id: "1000P3",
    name: "EVGA SuperNOVA 1000 P3 Platinum 1000W",
    img: "../../img/PSU/evga_supernova_1000_p3.png",
    url: "../../Components/PSU/1000P3.html",
  },
  {
    id: "1000P6", 
    name: "EVGA SuperNOVA 1000 P6 1000W Platinum",
    img: "../../img/PSU/evga_supernova_1000_p6.png",
    url: "../../Components/PSU/1000P6.html",
  },
  {
    id: "A650BN",
    name: "MSI MAG A650BN 650W Bronze",
    img: "../../img/PSU/msi_mag_a650bn.png",
    url: "../../Components/PSU/A650BN.html",
  },
  {
    id: "GEC",
    name: "COUGAR GEC 650 650W Gold",
    img: "../../img/PSU/cougar_gec_650_650w_gold.png",
    url: "../../Components/PSU/GEC.html",
  },
  {
    id: "VTE500",
    name: "Cougar VTE 500W Bronze",
    img: "../../img/PSU/cougar_vte500.png",
    url: "../../Components/PSU/VTE500.html",
  },
  {
    id: "ZM500",
    name: "Zalman MegaMax ZM500-TXII 500W",
    img: "../../img/PSU/zalman_megamax_500w_zm500txii.jpg",
    url: "../../Components/PSU/ZM500.html",
  },
  
  {
    id: "8702tb",
    name: "2TB Samsung SSD 870 EVO",
    img: "../../img/SSD/samsung_ssd_870_evo_2tb.jpg",
    url: "../../Components/SSD/870-2tb.html",
  },
  {
    id: "870500gb", 
    name: "Samsung SSD 870 EVO 500GB",
    img: "../../img/SSD/samsung_ssd_870_evo_500gb.jpg",
    url: "../../Components/SSD/870-500gb.html",
  },
  {
    id: "9801gbpro",
    name: "1TB Samsung 980 Pro M.2 NVMe",
    img: "../../img/SSD/1tb_samsung_980_pro_pcie_40.png",
    url: "../../Components/SSD/980-1tb-pro.html",
  },
  {
    id: "9801tb",
    name: "1TB Samsung SSD 980 PCIe 3.0",
    img: "../../img/SSD/1tb_samsung_ssd_980_pcie_30.jpg",
    url: "../../Components/SSD/980-1tb.html",
  },
  {
    id: "980500gb",
    name: "500GB Samsung SSD 980 PCIe 3.0",
    img: "../../img/SSD/500gb_samsung_ssd_980_pcie_30.jpg",
    url: "../../Components/SSD/980-500gb.html",
  },
  {
    id: "wd2tb",
    name: "2TB WD Blue SATA",
    img: "../../img/SSD/2tb_wd_blue_sata.jpg",
    url: "../../Components/SSD/WD-2tb.html",
  },
  //HDD
  {
    id: "TB5400",
    name: "1TB 5400rpm Western Digital Purple Surveillance",
    img: "../../img/HDD/1tb_5400rpm_western_digital_purple_surveillance.png",
    url: "../../Components/HDD/1TB_5400.html",
  },
  {
    id: "TB5900",
    name: "1TB 5900rpm Seagate IronWolf NAS",
    img: "../../img/HDD/1tb_5900rpm_seagate_ironwolf_nas.jpg",
    url: "../../Components/HDD/1TB_5900.html",
  },
  {
    id: "TB2",
    name: "2TB 5400 rpm Western Digital Red Plus NAS",
    img: "../../img/HDD/2tb_5400_rpm_western_digital_red_plus_nas.png",
    url: "../../Components/HDD/2TB_5400.html",
  },
  {
    id: "TB432",
    name: "2TB 7200rpm Western Digital Black",
    img: "../../img/HDD/2tb_7200_rpm_western_digital_black.png",
    url: "../../Components/HDD/2TB_7200.html",
  },
  {
    id: "TB59001",
    name: "4TB 7200rpm Western Digital Gold",
    img: "../../img/HDD/4tb_7200rpm_western_digital_gold.jpg",
    url: "../../Components/HDD/4TB_7200.html",
  },
  {
    id: "TB23",
    name: "4TB 7200rpm Western Digital Ultrastar 7К6",
    img: "../../img/HDD/4tb_7200rpm_hitachi_ultrastar_7k6.jpg",
    url: "../../Components/HDD/4TB_7200V.html",
  },
  {
    id: "razer1",
    name: "Razer BlackWidow V3 Tenkeyless, US Layout",
    img: "../../img/Top Products/Razer_BlackWidow_V3.png",
    url: "../../Peripherials/Keyboard/Razer_TK.html",
  },
  {
    id: "razer2",
    name: "Logitech G Pro",
    img: "../../img/Top Products/Logitech_GPro_Keyboard.jpg",
    url: "../../Peripherials/Keyboard/Logitech_Gpro.html",
  },
  {
    id: "gpro",
    name: "Razer BlackWidow V3, Green Mechanical Switch",
    img: "../../img/Keyboard/razer_v3.png",
    url: "../../Peripherials/Keyboard/Razer_Full.html",
  },
  {
    id: "corsair1",
    name: "Corsair K60 RGB PRO CHERRY VIOLA Black",
    img: "../../img/Keyboard/CH910D019NA.png",
    url: "../Peripherials/Keyboard/Corsair_K60.html",
  },
  {
    id: "asus1",
    name: "ASUS ROG Strix Scope RX TKL Wireless Deluxe",
    img: "../../img/Keyboard/90MP02J0BKUA01.png",
    url: "../Peripherials/Keyboard/Asus_Strix.html",
  },
  {
    id: "asus2",
    name: "АSUS ROG Strix Scope NX TKL Deluxe",
    img: "../../img/Keyboard/90MP00N6BKUA00.png",
    url: "../Peripherials/Keyboard/Asus_Scope.html",
  },
];